// GENERATED by test/oracle/walkforward_module.mjs from test/fixtures/walkforward.json and the frozen price
// fixtures' dates. Do not edit by hand: change the fixture, run the script, and commit both;
// test/t-walkforward-published.mjs fails while the two disagree.
//
// The published walk-forward run as it was computed: per set, the tickers, the schedule (each fit and each hold,
// first and last return day and the count of daily returns), the weights the app's own solver chose on each
// fit and held through the hold after it ("ship"), the held Sharpe ratio of each hold and of all holds joined,
// the joined Sharpe ratios of the same run solved exactly ("tight"), and each construction scored on the run's
// whole window under both solvers ("wholeWindow", in-sample). Weights are decimals in the set's
// ticker order; Sharpe ratios are annual and unrounded. The "As published" segment replays these and prints
// the published strings themselves from src/content/published.ts.

export type PublishedKey = "megacap5" | "sectors7" | "cross";

/** One fold: the fit's return days (every one before the hold) and the hold's, with their counts. */
export interface WalkFold {
  fitFirst: string;
  fitLast: string;
  fitRows: number;
  holdFirst: string;
  holdLast: string;
  rows: number;
}

/** One value per construction: equal weight, minimum variance, maximum Sharpe. */
export interface ByConstruction<T> {
  ew: T;
  gmv: T;
  tan: T;
}

export interface PublishedRun {
  key: PublishedKey;
  tickers: readonly string[];
  /** The first and last price day of the run. */
  firstBar: string;
  lastBar: string;
  folds: readonly WalkFold[];
  ship: {
    /** Per fold, the weights held through its hold. */
    weights: ByConstruction<readonly (readonly number[])[]>;
    /** Per fold, the Sharpe ratio of its held days alone. */
    foldSharpe: ByConstruction<readonly number[]>;
    /** The Sharpe ratio of every hold's days joined into one series. */
    sharpe: ByConstruction<number>;
  };
  /** The same schedule solved exactly: only the joined Sharpe ratios are kept. */
  tight: { sharpe: ByConstruction<number> };
  /**
   * Each construction scored on the run's whole window, first bar to last, the held-out years included: minimum
   * variance and maximum Sharpe fitted to that window by the app's own solver ("ship") and solved exactly
   * ("tight"), equal weight (no fit) scored on it. In-sample figures, at the run's rate; none of them is published.
   */
  wholeWindow: { ship: ByConstruction<number>; tight: ByConstruction<number> };
}

/** The annual risk-free rate the run used, as a decimal, in the maximum-Sharpe fit and in every score. */
export const WALK_RF = 0.02;

export const WALK_RUNS: readonly PublishedRun[] = [
  {
    key: "megacap5",
    tickers: ["AAPL", "MSFT", "GOOGL", "AMZN", "JPM"],
    firstBar: "2019-01-02",
    lastBar: "2026-09-04",
    folds: [
      { fitFirst: "2019-01-03", fitLast: "2020-12-31", fitRows: 504, holdFirst: "2021-01-04", holdLast: "2021-12-31", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2021-12-31", fitRows: 756, holdFirst: "2022-01-03", holdLast: "2023-01-03", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2023-01-03", fitRows: 1008, holdFirst: "2023-01-04", holdLast: "2024-01-04", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2024-01-04", fitRows: 1260, holdFirst: "2024-01-05", holdLast: "2025-01-06", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2025-01-06", fitRows: 1512, holdFirst: "2025-01-07", holdLast: "2026-01-08", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2026-01-08", fitRows: 1764, holdFirst: "2026-01-09", holdLast: "2026-09-04", rows: 165 },
    ],
    ship: {
      weights: {
        ew: [
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
        ],
        gmv: [
          [0, 0, 0.24242690967603175, 0.5118651371320584, 0.2457079531919099],
          [0, 2.3852447794681098e-18, 0.20769675622065123, 0.4842846965317565, 0.30801854724759237],
          [0.06094806139470181, 0.15100156261021838, 0.18580681673551352, 0.22209249723943636, 0.38015106202012994],
          [0.10945411551082553, 0.18072884055916824, 0.13424683850171648, 0.17411876501033743, 0.4014514404179524],
          [0.15315554935434236, 0.19584722081540928, 0.11519616694014463, 0.14309687817794037, 0.39270418471216334],
          [0.12304049114767567, 0.26431746638601494, 0.11757356062457026, 0.10303829420746227, 0.3920301876342769],
        ],
        tan: [
          [0.894645756757058, 0, 0, 0.10535424324294186, 0],
          [0.686737887244589, 0.2999886042876146, 0.01327350846779669, 0, 0],
          [0.8738942712828182, 0.12610572871718198, 0, 0, 1.5831519747347007e-16],
          [0.664937519073075, 0.32135768941129117, 5.0523821237824507e-17, 2.5261910618912253e-17, 0.013704791515633676],
          [0.6428149114865035, 0.18020501370219108, 0.004969155556988121, 2.425902360936316e-18, 0.17201091925431733],
          [0.3803760739486909, 0.0840774419225654, 0.2891823962194324, 0, 0.24636408790931127],
        ],
      },
      foldSharpe: { ew: [1.8096952359933, -1.0274328078818764, 2.238790142325768, 1.9970117598502477, 1.0601320179584763, 0.8521638679167942], gmv: [1.1432755138963024, -1.0800644198547003, 2.2316946178931345, 2.094012742801713, 1.1533955302420213, 0.8503581756841166], tan: [1.1637396964640272, -0.8725896503864715, 1.9855510554568074, 1.3820370706492193, 0.5569501105511522, 1.1427061709309656] },
      sharpe: { ew: 0.863951593948094, gmv: 0.7099522310419396, tan: 0.6594382342365396 },
    },
    tight: { sharpe: { ew: 0.863951593948094, gmv: 0.7097019311633335, tan: 0.6597098960132333 } },
    wholeWindow: { ship: { ew: 1.0189836724837185, gmv: 1.0342964505960122, tan: 1.10689172558172 }, tight: { ew: 1.0189836724837185, gmv: 1.0349758602019725, tan: 1.1068917766944997 } },
  },
  {
    key: "sectors7",
    tickers: ["XLK", "XLF", "XLV", "XLE", "XLI", "XLP", "XLY"],
    firstBar: "2019-01-02",
    lastBar: "2026-09-04",
    folds: [
      { fitFirst: "2019-01-03", fitLast: "2020-12-31", fitRows: 504, holdFirst: "2021-01-04", holdLast: "2021-12-31", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2021-12-31", fitRows: 756, holdFirst: "2022-01-03", holdLast: "2023-01-03", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2023-01-03", fitRows: 1008, holdFirst: "2023-01-04", holdLast: "2024-01-04", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2024-01-04", fitRows: 1260, holdFirst: "2024-01-05", holdLast: "2025-01-06", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2025-01-06", fitRows: 1512, holdFirst: "2025-01-07", holdLast: "2026-01-08", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2026-01-08", fitRows: 1764, holdFirst: "2026-01-09", holdLast: "2026-09-04", rows: 165 },
    ],
    ship: {
      weights: {
        ew: [
          [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285],
          [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285],
          [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285],
          [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285],
          [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285],
          [0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285],
        ],
        gmv: [
          [0, 3.8163916471489756e-17, 0.18651904717091009, 3.426078865054194e-17, 0, 0.7879102682850813, 0.025570684544008765],
          [0, 0, 0.22054996408241245, 0, 0, 0.7212595917956514, 0.05819044412193636],
          [0, 0, 0.2761944664987407, 0, 1.5711194070743628e-17, 0.7238055335012594, 0],
          [2.1144580110085895e-17, 1.9177560315464262e-17, 0.3015893670284002, 0, 0, 0.6984106329715998, 0],
          [4.357687842938723e-18, 7.709949226645522e-18, 0.31177838555144555, 1.1505266495743368e-17, 1.0998907424504649e-18, 0.6882216144485546, 8.70253658012423e-18],
          [1.2717723246990489e-17, 2.6452309547159766e-18, 0.2950506330044234, 0.006418273046183351, 0, 0.6910968187692823, 0.007434275180110999],
        ],
        tan: [
          [0.9999999999999978, 1.3183898417423734e-16, 5.204170427930421e-16, 0, 1.3183898417423734e-16, 1.1449174941446927e-15, 1.4710455076283324e-15],
          [1, 0, 0, 5.2909066017292616e-17, 0, 1.7520707107365752e-16, 0],
          [0.3624311141171884, 5.590458753161386e-16, 0.13874312344172715, 0.1271608811679889, 2.3631117265156066e-16, 0.3716648812730941, 7.444935354125387e-16],
          [0.9374970891121841, 9.915939780862186e-17, 1.561479526770772e-16, 0.06250291088781548, 0, 3.6723479877725734e-16, 0],
          [0.9572506197410575, 0, 1.3563873373732149e-17, 0.04274938025894226, 0, 3.217912047936977e-16, 3.1373833580133397e-17],
          [0.9064491048603094, 3.071623479811325e-17, 0, 0.04265178874778194, 0, 0.05089910639190846, 4.612697258134699e-17],
        ],
      },
      foldSharpe: { ew: [1.9956195895602744, -0.26727729994684357, 1.1754428945497446, 1.4893990801029378, 0.8199272825524693, 1.951300106380994], gmv: [1.5565238455483354, -0.24098873332356543, -0.029020932286067103, 0.6473008667702362, 0.47697825308992803, 0.9126358747527324], tan: [1.5387182417372511, -0.9172301012936576, 1.3669804319112444, 1.2338129132626314, 0.7749435522197547, 1.6005467954216934] },
      sharpe: { ew: 0.9145408937445818, gmv: 0.44950449275169363, tan: 0.6612779870699871 },
    },
    tight: { sharpe: { ew: 0.9145408937445818, gmv: 0.45014295707037477, tan: 0.6615601025413573 } },
    wholeWindow: { ship: { ew: 0.7952326605866853, gmv: 0.6295919207427929, tan: 0.9886355185761482 }, tight: { ew: 0.7952326605866853, gmv: 0.6323672742642833, tan: 0.9886359904851505 } },
  },
  {
    key: "cross",
    tickers: ["VTI", "AGG", "GLD", "VNQ", "EFA"],
    firstBar: "2019-01-02",
    lastBar: "2026-09-04",
    folds: [
      { fitFirst: "2019-01-03", fitLast: "2020-12-31", fitRows: 504, holdFirst: "2021-01-04", holdLast: "2021-12-31", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2021-12-31", fitRows: 756, holdFirst: "2022-01-03", holdLast: "2023-01-03", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2023-01-03", fitRows: 1008, holdFirst: "2023-01-04", holdLast: "2024-01-04", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2024-01-04", fitRows: 1260, holdFirst: "2024-01-05", holdLast: "2025-01-06", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2025-01-06", fitRows: 1512, holdFirst: "2025-01-07", holdLast: "2026-01-08", rows: 252 },
      { fitFirst: "2019-01-03", fitLast: "2026-01-08", fitRows: 1764, holdFirst: "2026-01-09", holdLast: "2026-09-04", rows: 165 },
    ],
    ship: {
      weights: {
        ew: [
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
          [0.2, 0.2, 0.2, 0.2, 0.2],
        ],
        gmv: [
          [0.034796992330491244, 0.9409017840448338, 0.024301223624675006, 8.24627895754401e-18, 3.1381442485832247e-19],
          [0.032102431738198885, 0.9507904316590902, 0.010235488980438313, 6.5052130349130266e-18, 0.006871647622272519],
          [0.005303696872334853, 0.9519949561977915, 0.01695492744906296, 6.613633252161577e-18, 0.025746419480810703],
          [0.023536146393373734, 0.9371116548139632, 0.01752847708745546, 4.1470733097570545e-18, 0.021823721705207615],
          [0.04207918490253332, 0.9352550759141662, 0.020223108197885246, 0, 0.0024426309854151023],
          [0.043537945781424815, 0.9347047570525954, 0.02175729716597981, 0, 0],
        ],
        tan: [
          [0.18169456937831774, 0.48938652039446745, 0.32891891022721403, 1.0370370320398485e-15, 0],
          [0.3728457767936555, 0.3288812694366639, 0.29827295376968094, 0, 0],
          [0.41314715494978316, 5.98522227733571e-17, 0.5868528450502168, 4.428842521115505e-18, 0],
          [0.46704221303951454, 4.216016002502735e-17, 0.5329577869604853, 6.436016507248362e-17, 1.0259664285654456e-16],
          [0.4449927208727324, 1.1955841649749545e-16, 0.5550072791272673, 0, 4.017773798246051e-17],
          [0.3440027816705707, 0, 0.6559972183294296, 2.2481976926306864e-16, 0],
        ],
      },
      foldSharpe: { ew: [1.3127614744022102, -1.0427247077111972, 1.1095854699216978, 1.261369634835459, 1.9017800059434635, 0.7540439789704378], gmv: [-0.80810056958009, -1.8711801925541596, 0.389272097968184, 0.21776227953577929, 1.506199402835695, -0.3347079521175365], tan: [0.063650826157308, -1.0400561844500547, 1.432276244915646, 2.1421053726013923, 2.5235577214776868, 0.2862591187267059] },
      sharpe: { ew: 0.7040987969347312, gmv: -0.24676141531893753, tan: 0.883245378952509 },
    },
    tight: { sharpe: { ew: 0.7040987969347312, gmv: -0.2483226122314665, tan: 0.8835151049869734 } },
    wholeWindow: { ship: { ew: 0.7763804400218186, gmv: 0.10570273199198635, tan: 1.1051247238038948 }, tight: { ew: 0.7763804400218186, gmv: 0.10344767036748391, tan: 1.105124724139498 } },
  },
];

/** The mega-caps' maximum-Sharpe portfolio fitted and scored on the run's whole window, unrounded. */
export const WALK_TANGENCY_IN_SAMPLE = 1.10689172558172;

/** One lookback of the Sensitivity tab: its label, its count of daily returns, and the weight. */
export interface LookbackWeight {
  label: string;
  rows: number;
  weight: number;
}

/** The mega-caps' maximum-Sharpe weight in AAPL at the Sensitivity tab's lookbacks, each ending on the last bar. */
export const WALK_APPLE: readonly LookbackWeight[] = [
  { label: "1 Year", rows: 252, weight: 0.41704037475520955 },
  { label: "2 Years", rows: 504, weight: 0.03849127461255524 },
  { label: "3 Years", rows: 756, weight: 0.06374936205998223 },
  { label: "5 Years", rows: 1260, weight: 0.20984788773146953 },
  { label: "Full Sample", rows: 1929, weight: 0.4484314737489139 },
];

/** The cross-asset minimum-variance weight in AGG through the hold that began in January 2022 (its fold index). */
export const WALK_AGG = { ticker: "AGG", fold: 1, weight: 0.9507904316590902 } as const;
