// Writes src/content/walkforward.ts, the data the walk-forward tab's "As published" segment replays, out of
// test/fixtures/walkforward.json (the published run as test/oracle/walkforward.py rebuilt it) and the dates of
// the frozen price fixtures (test/fixtures/prices-*.json), which give each fit and each hold its count of
// daily returns. Nothing is solved or rounded here: every number is the fixture's own, written back with
// JSON.stringify, which prints the shortest text that reads back to the same double.
//
//   node test/oracle/walkforward_module.mjs
//
// It writes the module and prints nothing. test/t-walkforward-published.mjs builds the text again with
// build() and requires it to equal the committed file byte for byte, so a fixture regenerated without a
// fresh run of this script goes red.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

const FIXTURES = new URL("../fixtures/", import.meta.url);
const OUT = new URL("../../src/content/walkforward.ts", import.meta.url);
// The run's key in walkforward.json -> the price fixture holding the same tickers.
const PRICES = { megacap5: "megacap5", sectors7: "sectors", cross: "cross" };

const read = (url) => JSON.parse(readFileSync(url, "utf8"));
const num = (x) => {
  if (!Number.isFinite(x)) throw new Error(`not a finite number: ${x}`);
  return JSON.stringify(x);
};
const str = (s) => JSON.stringify(s);
const list = (xs, f) => `[${xs.map(f).join(", ")}]`;

// The return days of a run: the price fixture's days from the run's first bar through its last, less the
// first (a return needs the close before it).
function returnDays(key, entry) {
  const px = read(new URL(`prices-${PRICES[key]}.json`, FIXTURES));
  const days = px.rows.map((r) => r[0]).filter((d) => d >= entry.first_bar && d <= entry.last_bar);
  if (days[0] !== entry.first_bar || days.at(-1) !== entry.last_bar) throw new Error(`${key}: the price fixture does not span the run`);
  return days.slice(1);
}

function folds(key, entry) {
  const days = returnDays(key, entry);
  const at = (d) => {
    const i = days.indexOf(d);
    if (i < 0) throw new Error(`${key}: ${d} is not a return day`);
    return i;
  };
  return entry.folds.map((f) => {
    const hold = [at(f.hold_first), at(f.hold_last)];
    const fitTo = at(f.fit_last);
    if (fitTo + 1 !== hold[0]) throw new Error(`${key}: a fit does not end the day before its hold`);
    return { fitFirst: days[0], fitLast: f.fit_last, fitRows: fitTo + 1, holdFirst: f.hold_first, holdLast: f.hold_last, rows: hold[1] - hold[0] + 1 };
  });
}

const CORE = ["ew", "gmv", "tan"];

function runText(key, entry) {
  const fs = folds(key, entry)
    .map((f) => `      { fitFirst: ${str(f.fitFirst)}, fitLast: ${str(f.fitLast)}, fitRows: ${f.fitRows}, holdFirst: ${str(f.holdFirst)}, holdLast: ${str(f.holdLast)}, rows: ${f.rows} },`)
    .join("\n");
  const weights = CORE.map((k) => `        ${k}: [\n${entry.ship.weights[k].map((w) => `          ${list(w, num)},`).join("\n")}\n        ],`).join("\n");
  const per = (obj, f) => CORE.map((k) => `${k}: ${f(obj[k])}`).join(", ");
  return [
    "  {",
    `    key: ${str(key)},`,
    `    tickers: ${list(entry.tickers, str)},`,
    `    firstBar: ${str(entry.first_bar)},`,
    `    lastBar: ${str(entry.last_bar)},`,
    "    folds: [",
    fs,
    "    ],",
    "    ship: {",
    "      weights: {",
    weights,
    "      },",
    `      foldSharpe: { ${per(entry.ship.fold_sharpe, (xs) => list(xs, num))} },`,
    `      sharpe: { ${per(entry.ship.sharpe, num)} },`,
    "    },",
    `    tight: { sharpe: { ${per(entry.tight.sharpe, num)} } },`,
    `    wholeWindow: { ship: { ${per(entry.whole_window.ship.sharpe, num)} }, tight: { ${per(entry.whole_window.tight.sharpe, num)} } },`,
    "  },",
  ].join("\n");
}

/** The module's text, built from the fixtures as they are on disk. */
export function build() {
  const wf = read(new URL("walkforward.json", FIXTURES));
  const keys = Object.keys(wf.sets);
  for (const k of keys) if (!PRICES[k]) throw new Error(`no price fixture for ${k}`);

  const mega = wf.sets.megacap5;
  const cross = wf.sets.cross;
  const agg = cross.tickers.indexOf("AGG");
  const into2022 = cross.folds.findIndex((f) => f.hold_first.startsWith("2022-01"));
  if (agg < 0 || into2022 < 0 || cross.ship.weights.gmv[into2022][agg] !== cross.ship.gmv_agg_into_2022)
    throw new Error("cross: the stored AGG weight is not the minimum-variance weight of the hold from January 2022");
  // The whole-window block's mega-cap maximum Sharpe is the same computation as the in-sample tangency the page
  // quotes beside 1.107, so the two must be one double under each solver.
  for (const o of ["ship", "tight"])
    if (mega.whole_window?.[o]?.sharpe?.tan !== mega[o].in_sample_tangency)
      throw new Error(`megacap5 ${o}: the whole-window maximum Sharpe is not the recorded in-sample tangency`);

  return `// GENERATED by test/oracle/walkforward_module.mjs from test/fixtures/walkforward.json and the frozen price
// fixtures' dates. Do not edit by hand: change the fixture, run the script, and commit both;
// test/t-walkforward-published.mjs fails while the two disagree.
//
// The published walk-forward run as it was computed: per set, the tickers, the schedule (each fit and each hold,
// first and last return day and the count of daily returns), the weights the app's own solver chose on each
// fit and held through the hold after it ("ship"), the held Sharpe ratio of each hold and of all holds joined,
// the joined Sharpe ratios of the same run solved exactly ("tight"), and each construction scored on the run's
// whole window under both solvers ("wholeWindow", in-sample). Weights are decimals in the set's
// ticker order; Sharpe ratios are annual and unrounded. The "As published" segment replays these and prints
// the published strings themselves from src/content/published.ts.

export type PublishedKey = ${keys.map(str).join(" | ")};

/** One fold: the fit's return days (every one before the hold) and the hold's, with their counts. */
export interface WalkFold {
  fitFirst: string;
  fitLast: string;
  fitRows: number;
  holdFirst: string;
  holdLast: string;
  rows: number;
}

/** One value per construction: equal weight, minimum variance, maximum Sharpe. */
export interface ByConstruction<T> {
  ew: T;
  gmv: T;
  tan: T;
}

export interface PublishedRun {
  key: PublishedKey;
  tickers: readonly string[];
  /** The first and last price day of the run. */
  firstBar: string;
  lastBar: string;
  folds: readonly WalkFold[];
  ship: {
    /** Per fold, the weights held through its hold. */
    weights: ByConstruction<readonly (readonly number[])[]>;
    /** Per fold, the Sharpe ratio of its held days alone. */
    foldSharpe: ByConstruction<readonly number[]>;
    /** The Sharpe ratio of every hold's days joined into one series. */
    sharpe: ByConstruction<number>;
  };
  /** The same schedule solved exactly: only the joined Sharpe ratios are kept. */
  tight: { sharpe: ByConstruction<number> };
  /**
   * Each construction scored on the run's whole window, first bar to last, the held-out years included: minimum
   * variance and maximum Sharpe fitted to that window by the app's own solver ("ship") and solved exactly
   * ("tight"), equal weight (no fit) scored on it. In-sample figures, at the run's rate; none of them is published.
   */
  wholeWindow: { ship: ByConstruction<number>; tight: ByConstruction<number> };
}

/** The annual risk-free rate the run used, as a decimal, in the maximum-Sharpe fit and in every score. */
export const WALK_RF = ${num(wf.rf)};

export const WALK_RUNS: readonly PublishedRun[] = [
${keys.map((k) => runText(k, wf.sets[k])).join("\n")}
];

/** The mega-caps' maximum-Sharpe portfolio fitted and scored on the run's whole window, unrounded. */
export const WALK_TANGENCY_IN_SAMPLE = ${num(mega.ship.in_sample_tangency)};

/** One lookback of the Sensitivity tab: its label, its count of daily returns, and the weight. */
export interface LookbackWeight {
  label: string;
  rows: number;
  weight: number;
}

/** The mega-caps' maximum-Sharpe weight in AAPL at the Sensitivity tab's lookbacks, each ending on the last bar. */
export const WALK_APPLE: readonly LookbackWeight[] = [
${mega.sensitivity_apple.windows.map((w) => `  { label: ${str(w.label)}, rows: ${w.bars}, weight: ${num(w.tangency_aapl)} },`).join("\n")}
];

/** The cross-asset minimum-variance weight in AGG through the hold that began in January 2022 (its fold index). */
export const WALK_AGG = { ticker: ${str(cross.tickers[agg])}, fold: ${into2022}, weight: ${num(cross.ship.gmv_agg_into_2022)} } as const;
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) writeFileSync(fileURLToPath(OUT), build());
